default:
	g++ main.cpp -o client.out -lboost_system -lpthread

san:
	g++ main.cpp -o clientsan.out -lboost_system -lpthread

opt:
	g++ main.cpp -o client.out -lboost_system -lpthread -O2

clean:
	rm -rf *.out