default:
	g++ main.cpp -o server.out -lboost_system -lpthread

san:
	g++ main.cpp -o serversan.out -lboost_system -lpthread

opt:
	g++ main.cpp -o server.out -lboost_system -lpthread -O2

clean:
	rm -rf *.out